# Generated by Django 2.0.7 on 2018-08-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Exercise name')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime created')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='days.Day')),
            ],
        ),
    ]
