# Generated by Django 2.0.7 on 2018-08-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime updated')),
            ],
        ),
    ]
