# Generated by Django 2.0.7 on 2018-08-19 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_plan_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of day')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime created')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
        ),
    ]
